kind: Service
apiVersion: v1
metadata:
  name: cowbull-svc
  labels:
    run: cowbull
    app: cowbull
    tier: frontend
spec:
  selector:
    app: cowbull
    tier: frontend
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
