#!/usr/bin/env bash
version="2"
rg="k8ClusterRG"$version
clusterName="k8Cluster"$version
masters="1"
agents="1"
location="eastus"
machineType="Standard_A2"
dnsPrefix="dasanderk8"
publicIpDNS="cowbull-azure"
keyfile=~/.ssh/id_rsa
echo ""
echo "Deploy CowBull game to Kubernetes cluster running on Azure"
echo "=========================================================="
echo ""
echo "Configuration will be set as follows:"
echo "-------------------------------------"
echo ""
echo "resource group:   "$rg
echo "cluster name  :   "$clusterName
echo "master count  :   "$masters
echo "agent count   :   "$agents
echo "location      :   "$location
echo "machine type  :   "$machineType
echo "dns prefix    :   "$dnsPrefix
echo "cowbull dns   :   "$publicIpDNS"."$dnsPrefix"."$location".cloudapp.azure.com"
echo "private key   :   "$keyfile
echo ""
read -p "Continue (y for yes, anything else to quit)? " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo "Exiting".
    exit 0
fi
echo ""
echo "1. Create the resource group"$rg
echo ""
az group create --name $rg --location $location
echo ""
echo "2. Create the cluster. --resource-group "$rg" --clusterName "$clusterName" --master-count "$masters" --agent-count "$agents
az acs create \
  --orchestrator-type kubernetes \
  --resource-group $rg \
  --name $clusterName \
  --master-count $masters \
  --agent-count $agents \
  --generate-ssh-keys \
  --dns-prefix $dnsPrefix \
  --agent-vm-size $machineType
echo ""
echo "3. Add your private key ("$keyfile")"
ssh-add -k $keyfile
echo ""
echo "4. Get kubernetes credentials to configure kubectl"
az acs kubernetes get-credentials --resource-group=$rg --name=$clusterName
echo ""
echo ""
echo "Done."
echo ""
echo "Next steps:"
echo "1. Wait for the cluster to be ready > kubectl get nodes --watch"
echo "2. Run step 2 to deploy services    > ./2-deploy-services"
echo ""
echo "When you're done:"
echo "1. Run step 3 to remove services    > ./3-remove-services"
echo "2. Run the teardown script          > ./4-spindown-cluster"
echo "3. Verify the group is cleared      > az group list"
echo ""
