#!/usr/bin/env bash
source setup_variables
echo ""
echo "Deploy CowBull game to Kubernetes cluster running on Azure"
echo "=========================================================="
echo ""
echo "Configuration will be set as follows:"
echo "-------------------------------------"
echo ""
echo "resource group:   "$rg
echo "cluster name  :   "$clusterName
echo "master count  :   "$masters
echo "agent count   :   "$agents
echo "location      :   "$location
echo "machine type  :   "$machineType
echo "dns prefix    :   "$dnsPrefix
echo "cowbull dns   :   "$publicIpDNS"."$dnsPrefix"."$location".cloudapp.azure.com"
echo "private key   :   "$keyfile
echo ""
read -p "Continue (y for yes, anything else to quit)? " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo "Exiting".
    exit 0
fi
echo ""
echo "1. Removng configuration and services"
kubectl delete configmap cowbull-config --ignore-not-found
kubectl delete \
    -f redis-deploy.yml \
    --ignore-not-found
kubectl delete \
    -f redis-service.yml \
    --ignore-not-found
kubectl delete \
    -f cowbull-deploy.yml \
    --ignore-not-found
kubectl delete \
    -f cowbull-service.yml \
    --ignore-not-found
kubectl delete \
    -f webapp-deploy.yml \
    --ignore-not-found
echo ""
echo "2. Remove CowBull web app and network interfaces."
kubectl delete service webapp --ignore-not-found
echo ""
echo "3. Sleep for 60 seconds to give time for the service to clear "
echo ""
echo "   NOTE: If an error is reported that the Public IP is in use,"
echo "         You may need to wait for the service to clear and/or"
echo "         manually remove it. If you are tearing down the"
echo "         cluster, simply move to step 4."
echo ""
echo "         az network public-ip delete --name "$dnsPrefix"-webapp-pip -g "$autoGroup
echo ""
sleep 60
echo ""
echo "4. Delete network IP"
az network public-ip delete --name $dnsPrefix"-webapp-pip" -g $autoGroup
echo ""
echo "Done."
echo ""
echo "When you're done:"
echo "1. Run the teardown script          > ./4-spindown-cluster"
echo "2. Verify the group is cleared      > az group list"
echo ""
