#!/usr/bin/env bash
source setup_variables
echo ""
echo "Deploy CowBull game to Kubernetes cluster running locally"
echo "========================================================="
echo ""
read -p "Continue (y for yes, anything else to quit)? " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo "Exiting".
    exit 0
fi
echo ""
echo "1. Remove any existing configuration and services"
kubectl delete configmap cowbull-config --ignore-not-found
kubectl delete \
    -f scripts/redis-deploy.yml \
    --ignore-not-found
kubectl delete \
    -f scripts/redis-service.yml \
    --ignore-not-found
kubectl delete \
    -f scripts/cowbull-deploy.yml \
    --ignore-not-found
kubectl delete \
    -f scripts/cowbull-service.yml \
    --ignore-not-found
kubectl delete \
    -f scripts/webapp-deploy.yml \
    --ignore-not-found
kubectl delete \
    -f scripts/webapp-service.yml \
    --ignore-not-found
echo ""
echo "2. Create configuration map"
kubectl create configmap cowbull-config \
  --from-file=cowbull.cfg
echo ""
echo "3. Deploy Redis"
kubectl create -f scripts/redis-service.yml
kubectl create -f scripts/redis-deploy.yml
echo ""
echo "4. Deploy CowBull"
kubectl create -f scripts/cowbull-service.yml
kubectl create -f scripts/cowbull-deploy.yml
echo ""
echo "5. Deploy CowBull web app"
kubectl create -f scripts/webapp-deploy.yml
kubectl expose deployment webapp --type=LoadBalancer
echo ""
echo "Done."
echo ""
