kind: ConfigMap
apiVersion: v1
metadata:
    name: cowbull-config
    namespace: default
data:
    cowbull.cfg: '{
      "LOGGING_FORMAT": "%(asctime)s %(levelname)s: %(message)s ",
      "LOGGING_LEVEL": 10,
      "PERSISTER": {"engine_name": "redis", "parameters": {"host": "redis", "port": 6379, "master_port": 26379, "db": 0}}
    }'
