apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: ${REDIS_REPLICAS}
  serviceName: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - command: [bash, -c, . /redis-config/init.sh]
        image: dsanderscan/python_cowbull_redis${REDIS_TAGS}
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - mountPath: /redis-config
          name: config
        - mountPath: /redis-data
          name: data
      - command: [bash, -c, . /redis-config/sentinel.sh]
        image: dsanderscan/python_cowbull_redis${REDIS_TAGS}
        name: sentinel
        volumeMounts:
        - mountPath: /redis-config
          name: config
      volumes:
      - configMap:
          defaultMode: 420
          name: redis-config
        name: config
      - emptyDir:
        name: data
