apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: webapp
        run: webapp
        tier: webappFrontend
    spec:
      containers:
      - name: webapp
        image: dsanderscan/cowbull_webapp:latest
        resources:
          requests:
            cpu: '0.1'
            memory: 40Mi
        env:
        - name: LOGGING_LEVEL
          value: "10"
        - name: COWBULL_SERVER
          value: "cowbull-svc"
        - name: COWBULL_PORT
          value: "8080"
        ports:
        - containerPort: 8080
